### ISSUE TITLE
Output directory different than the current directory throws IOError

### ISSUE THREAD

**Issue by cpauvert** [LM-UGent/SPeDE#6]
Hi,
Thanks for developing SPeDE! I've ran the following command with the example preprocessed dataset in `Spectrum_Processing/voorbeeld-invoer-merged`:

```bash
# in SPeDE directory
python3 Spectrum_Processing/SPeDE.py GUI/ppmc_interval_index.csv Spectrum_Processing/voorbeeld-invoer-merged/ output_test/
```

SPeDE complains that the output file does not exists with the following error:

```python
Traceback (most recent call last):
  File "/SPeDE/Spectrum_Processing/../Spectrum_Processing/postProcess.py", line 109, in format_CSV
    outfile=open(outfile_path,"w+")
FileNotFoundError: [Errno 2] No such file or directory: 'output_test/2022_11_21_10_19_38_SPeDE_output.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Spectrum_Processing/SPeDE.py", line 123, in <module>
    main(args.intervals, args.project_directory, args.output_directory, args.peaks, args.density, args.local,args.cutoff, args.validate,
  File "Spectrum_Processing/SPeDE.py", line 70, in main
    cluster.write_clustering(output_format)
  File "/SPeDE/Spectrum_Processing/../Spectrum_Processing/cluster.py", line 195, in write_clustering
    format_CSV(self.refer_array, self.group_array, os.path.join(self.output_directory ,self.out_name), self.provider)
  File "/SPeDE/Spectrum_Processing/../Spectrum_Processing/postProcess.py", line 111, in format_CSV
    raise IOError
OSError
```

However, when no output directory is provided, as the following command, the output file is created in the current working directory:

```bash
# in SPeDE directory
python3 Spectrum_Processing/SPeDE.py GUI/ppmc_interval_index.csv Spectrum_Processing/voorbeeld-invoer-merged/ .
```
This can be problematic when one wants to organize folders by projects for instance.
Best, 
Charlie

**Comment by esdpoort** [comment]
Thank you for signaling this @cpauvert!

I was able to reproduce the error you observed, but only with the command-line version and only if the output directory did not exist yet. SPeDE expects the output folder to exist before starting the analysis but this was not specified in the documentation. Therefore, the command-line version of SPeDE has been modified to check if the provided output directory exists and if not, to create it.

**Comment by cpauvert** [comment]
Thank you for fixing these issues @esdpoort !
